; TeXture installer (PowerPoint + Word + offline OCR engine).
; Build with installer\build.ps1 (compiles the solution Release, extracts signing keys, runs ISCC).
;
; Differences from the v1.2.3 installer:
;  - Registry-based VSTO deployment (|vstolocal) instead of chaining two ClickOnce setup.exe files.
;  - No changes to the machine-wide .NET TrustManager prompting levels (v1.2.3 enabled them for
;    Internet/UntrustedSites). Trust for the installing user comes from a VSTO inclusion-list entry.
;  - Never kills PowerPoint/Word: asks the user to close them.
;  - Real uninstaller (Apps & features), removes registry entries and files.

#define AppVersion "2.0.1"
#define Root "..\.."
#define Assets "assets"
#define PptBin "..\PowerPoint\bin\Release"
#define WordBin "..\Word\bin\Release"
#define Capture "..\capture"
#define PptName "TeXture (PowerPoint)"
#define WordName "TeXture (Word)"

; Public keys of the manifest-signing certificates (generated by build.ps1).
#include "keys.generated.iss"

[Setup]
AppId={{8D4C2A7E-5B1F-4E3A-9C6D-7F2E1A0B3C4D}
AppName=TeXture
AppVersion={#AppVersion}
AppVerName=TeXture {#AppVersion}
AppPublisher=Allariala
AppSupportURL=https://allariala.github.io/TeXture/
DefaultDirName={autopf}\TeXture
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x86compatible x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir=Output
OutputBaseFilename=TeXture_Install_v{#AppVersion}
SetupIconFile={#Assets}\TeXture_icon.ico
LicenseFile={#Root}\LICENSE
UninstallDisplayIcon={app}\TeXture_icon.ico
UninstallDisplayName=TeXture {#AppVersion} (PowerPoint & Word)
Compression=lzma2/fast
SolidCompression=no
WizardStyle=modern
CloseApplications=no

[Languages]
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[InstallDelete]
; Leftovers of the v1.2.x layout (the OCR engine folder is replaced as a whole).
Type: filesandordirs; Name: "{app}\capture_server"

[Files]
Source: "{#Assets}\TeXture_icon.ico"; DestDir: "{app}"; Flags: ignoreversion
; Public part of the manifest-signing certificate (valid until 2126); registered machine-wide in [Run].
Source: "{#Assets}\TeXture-signing.cer"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\THIRD_PARTY_NOTICES.md"; DestDir: "{app}"; Flags: ignoreversion
; PowerPoint add-in (assembly, VSTO manifests, WebView2, shared UI)
Source: "{#PptBin}\*.dll"; DestDir: "{app}\PowerPoint"; Flags: ignoreversion
Source: "{#PptBin}\*.manifest"; DestDir: "{app}\PowerPoint"; Flags: ignoreversion
Source: "{#PptBin}\*.vsto"; DestDir: "{app}\PowerPoint"; Flags: ignoreversion
Source: "{#PptBin}\runtimes\*"; DestDir: "{app}\PowerPoint\runtimes"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PptBin}\ui\*"; DestDir: "{app}\PowerPoint\ui"; Flags: ignoreversion recursesubdirs createallsubdirs
; Word add-in
Source: "{#WordBin}\*.dll"; DestDir: "{app}\Word"; Flags: ignoreversion
Source: "{#WordBin}\*.manifest"; DestDir: "{app}\Word"; Flags: ignoreversion
Source: "{#WordBin}\*.vsto"; DestDir: "{app}\Word"; Flags: ignoreversion
Source: "{#WordBin}\runtimes\*"; DestDir: "{app}\Word\runtimes"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#WordBin}\ui\*"; DestDir: "{app}\Word\ui"; Flags: ignoreversion recursesubdirs createallsubdirs
; Offline OCR engine (PyInstaller build of windows\capture, GPL-3.0 because it bundles texify; see
; THIRD_PARTY_NOTICES.md). Binaries are not in git: build them or copy them into windows\capture (see README).
#if DirExists(Capture + "\dist\texture_capture")
; API v2 engine, one-folder PyInstaller build (texture_capture.spec)
Source: "{#Capture}\dist\texture_capture\*"; DestDir: "{app}\capture_server"; Flags: ignoreversion recursesubdirs createallsubdirs
#else
; fallback: v1.2.3 one-file engine (the add-in runs it in legacy mode)
Source: "{#Capture}\dist\texture_capture.exe"; DestDir: "{app}\capture_server"; Flags: ignoreversion
#endif
Source: "{#Capture}\texify_model.pt"; DestDir: "{app}\capture_server"; Flags: ignoreversion
Source: "{#Capture}\models\*.json"; DestDir: "{app}\capture_server\models"; Flags: ignoreversion

[Registry]
; Install location (the add-ins use it to find the OCR engine).
Root: HKLM64; Subkey: "SOFTWARE\TeXture"; ValueType: string; ValueName: "InstallDir"; ValueData: "{app}"; Flags: uninsdeletekey; Check: IsWin64
Root: HKLM32; Subkey: "SOFTWARE\TeXture"; ValueType: string; ValueName: "InstallDir"; ValueData: "{app}"; Flags: uninsdeletekey

; All-users add-in registration, for 64-bit and 32-bit Office.
Root: HKLM64; Subkey: "SOFTWARE\Microsoft\Office\PowerPoint\Addins\{#PptName}"; ValueType: string; ValueName: "FriendlyName"; ValueData: "{#PptName}"; Flags: uninsdeletekey; Check: IsWin64
Root: HKLM64; Subkey: "SOFTWARE\Microsoft\Office\PowerPoint\Addins\{#PptName}"; ValueType: string; ValueName: "Description"; ValueData: "LaTeX Editor for PowerPoint"; Check: IsWin64
Root: HKLM64; Subkey: "SOFTWARE\Microsoft\Office\PowerPoint\Addins\{#PptName}"; ValueType: dword; ValueName: "LoadBehavior"; ValueData: "3"; Check: IsWin64
Root: HKLM64; Subkey: "SOFTWARE\Microsoft\Office\PowerPoint\Addins\{#PptName}"; ValueType: string; ValueName: "Manifest"; ValueData: "{code:ManifestUrl|PowerPoint\{#PptName}.vsto}|vstolocal"; Check: IsWin64
Root: HKLM32; Subkey: "SOFTWARE\Microsoft\Office\PowerPoint\Addins\{#PptName}"; ValueType: string; ValueName: "FriendlyName"; ValueData: "{#PptName}"; Flags: uninsdeletekey
Root: HKLM32; Subkey: "SOFTWARE\Microsoft\Office\PowerPoint\Addins\{#PptName}"; ValueType: string; ValueName: "Description"; ValueData: "LaTeX Editor for PowerPoint"
Root: HKLM32; Subkey: "SOFTWARE\Microsoft\Office\PowerPoint\Addins\{#PptName}"; ValueType: dword; ValueName: "LoadBehavior"; ValueData: "3"
Root: HKLM32; Subkey: "SOFTWARE\Microsoft\Office\PowerPoint\Addins\{#PptName}"; ValueType: string; ValueName: "Manifest"; ValueData: "{code:ManifestUrl|PowerPoint\{#PptName}.vsto}|vstolocal"

Root: HKLM64; Subkey: "SOFTWARE\Microsoft\Office\Word\Addins\{#WordName}"; ValueType: string; ValueName: "FriendlyName"; ValueData: "{#WordName}"; Flags: uninsdeletekey; Check: IsWin64
Root: HKLM64; Subkey: "SOFTWARE\Microsoft\Office\Word\Addins\{#WordName}"; ValueType: string; ValueName: "Description"; ValueData: "LaTeX Editor for Word"; Check: IsWin64
Root: HKLM64; Subkey: "SOFTWARE\Microsoft\Office\Word\Addins\{#WordName}"; ValueType: dword; ValueName: "LoadBehavior"; ValueData: "3"; Check: IsWin64
Root: HKLM64; Subkey: "SOFTWARE\Microsoft\Office\Word\Addins\{#WordName}"; ValueType: string; ValueName: "Manifest"; ValueData: "{code:ManifestUrl|Word\{#WordName}.vsto}|vstolocal"; Check: IsWin64
Root: HKLM32; Subkey: "SOFTWARE\Microsoft\Office\Word\Addins\{#WordName}"; ValueType: string; ValueName: "FriendlyName"; ValueData: "{#WordName}"; Flags: uninsdeletekey
Root: HKLM32; Subkey: "SOFTWARE\Microsoft\Office\Word\Addins\{#WordName}"; ValueType: string; ValueName: "Description"; ValueData: "LaTeX Editor for Word"
Root: HKLM32; Subkey: "SOFTWARE\Microsoft\Office\Word\Addins\{#WordName}"; ValueType: dword; ValueName: "LoadBehavior"; ValueData: "3"
Root: HKLM32; Subkey: "SOFTWARE\Microsoft\Office\Word\Addins\{#WordName}"; ValueType: string; ValueName: "Manifest"; ValueData: "{code:ManifestUrl|Word\{#WordName}.vsto}|vstolocal"

; VSTO inclusion list for the installing user (belt and braces; the certificate registered in [Run]
; already covers every user on the PC). Certificate valid until 2126 (new-signing-cert.ps1).
Root: HKCU; Subkey: "Software\Microsoft\VSTO\Security\Inclusion\{{3C1B7E52-9A4D-4F61-8B2E-6D0A5C9F1E73}"; ValueType: string; ValueName: "Url"; ValueData: "{code:ManifestUrl|PowerPoint\{#PptName}.vsto}"; Flags: uninsdeletekey; Check: HasKey('{#PptPublicKey}')
Root: HKCU; Subkey: "Software\Microsoft\VSTO\Security\Inclusion\{{3C1B7E52-9A4D-4F61-8B2E-6D0A5C9F1E73}"; ValueType: string; ValueName: "PublicKey"; ValueData: "{#PptPublicKey}"; Check: HasKey('{#PptPublicKey}')
Root: HKCU; Subkey: "Software\Microsoft\VSTO\Security\Inclusion\{{7F4A9D10-2C6B-4E85-A1D3-9B5E0C7F2A64}"; ValueType: string; ValueName: "Url"; ValueData: "{code:ManifestUrl|Word\{#WordName}.vsto}"; Flags: uninsdeletekey; Check: HasKey('{#WordPublicKey}')
Root: HKCU; Subkey: "Software\Microsoft\VSTO\Security\Inclusion\{{7F4A9D10-2C6B-4E85-A1D3-9B5E0C7F2A64}"; ValueType: string; ValueName: "PublicKey"; ValueData: "{#WordPublicKey}"; Check: HasKey('{#WordPublicKey}')

[Run]
; Trust TeXture's own signing certificate on this PC (author's decision, announced on the Ready page):
; the add-ins then load for every Windows user without a VSTO trust prompt, permanently. The certificate
; is not a CA (basicConstraints ca=false) and is only valid for code signing; the uninstaller removes it.
Filename: "{sys}\certutil.exe"; Parameters: "-f -addstore Root ""{app}\TeXture-signing.cer"""; Flags: runhidden waituntilterminated; StatusMsg: "Registering the TeXture signing certificate..."
Filename: "{sys}\certutil.exe"; Parameters: "-f -addstore TrustedPublisher ""{app}\TeXture-signing.cer"""; Flags: runhidden waituntilterminated

[UninstallRun]
Filename: "{sys}\taskkill.exe"; Parameters: "/F /IM texture_capture.exe"; Flags: runhidden; RunOnceId: "StopOcr"
Filename: "{sys}\certutil.exe"; Parameters: "-delstore TrustedPublisher {#CertThumbprint}"; Flags: runhidden; RunOnceId: "UntrustPublisher"
Filename: "{sys}\certutil.exe"; Parameters: "-delstore Root {#CertThumbprint}"; Flags: runhidden; RunOnceId: "UntrustRoot"

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Code]
function ManifestUrl(Param: String): String;
var
  P: String;
begin
  P := ExpandConstant('{app}\') + Param;
  StringChangeEx(P, '\', '/', True);
  Result := 'file:///' + P;
end;

function HasKey(Value: String): Boolean;
begin
  Result := Length(Value) > 20;
end;

function IsProcessRunning(ExeName: String): Boolean;
var
  ResultCode: Integer;
begin
  Exec(ExpandConstant('{cmd}'), '/c tasklist /FI "IMAGENAME eq ' + ExeName + '" | find /I "' + ExeName + '"',
       '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := ResultCode = 0;
end;

function VstoRuntimeInstalled(): Boolean;
begin
  Result := RegKeyExists(HKLM64, 'SOFTWARE\Microsoft\VSTO Runtime Setup\v4R') or
            RegKeyExists(HKLM32, 'SOFTWARE\Microsoft\VSTO Runtime Setup\v4R') or
            RegKeyExists(HKLM64, 'SOFTWARE\Microsoft\VSTO Runtime Setup\v4') or
            RegKeyExists(HKLM32, 'SOFTWARE\Microsoft\VSTO Runtime Setup\v4');
end;

function WebView2Installed(): Boolean;
var
  Version: String;
begin
  Result := RegQueryStringValue(HKLM32, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) or
            RegQueryStringValue(HKLM64, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) or
            RegQueryStringValue(HKCU, 'Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version);
  Result := Result and (Version <> '') and (Version <> '0.0.0.0');
end;

function InitializeSetup(): Boolean;
begin
  Result := True;
  if not VstoRuntimeInstalled() then
    MsgBox('Visual Studio 2010 Tools for Office Runtime이 설치되어 있지 않은 것 같습니다.' + #13#10 +
           '설치는 계속되지만, 추가 기능이 로드되지 않으면 Microsoft에서 "VSTO Runtime"을 설치해 주세요.',
           mbInformation, MB_OK);
  if not WebView2Installed() then
    MsgBox('Microsoft Edge WebView2 런타임이 설치되어 있지 않은 것 같습니다.' + #13#10 +
           '편집기 화면을 표시하려면 WebView2 런타임(Evergreen)을 설치해 주세요.',
           mbInformation, MB_OK);
end;

// Tell the user what happens to certificate trust before anything is installed.
function UpdateReadyMemo(Space, NewLine, MemoUserInfoInfo, MemoDirInfo, MemoTypeInfo, MemoComponentsInfo, MemoGroupInfo, MemoTasksInfo: String): String;
begin
  Result := MemoDirInfo + NewLine + NewLine +
    'Certificate / 인증서:' + NewLine +
    Space + 'The TeXture code-signing certificate (CN=TeXture Add-in Signing, valid until 2126)' + NewLine +
    Space + 'is added to "Trusted Root Certification Authorities" and "Trusted Publishers"' + NewLine +
    Space + 'so the add-ins load without security prompts. It is removed on uninstall.' + NewLine +
    Space + 'TeXture 서명 인증서를 신뢰할 수 있는 루트/게시자 저장소에 등록합니다 (제거 시 삭제).';
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  // Never close Office on the user's behalf: unsaved work would be lost.
  if IsProcessRunning('POWERPNT.EXE') or IsProcessRunning('WINWORD.EXE') then
  begin
    Result := 'PowerPoint 또는 Word가 실행 중입니다.' + #13#10 +
              '작업을 저장하고 두 프로그램을 모두 종료한 뒤 [뒤로] → [다음]을 눌러 다시 시도해 주세요.';
    Exit;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssInstall then
  begin
    // Our own OCR engine may hold files open; it is stateless and safe to stop.
    Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM texture_capture.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    // Per-user registrations of v1.2.x (ClickOnce) would override the new all-users registration.
    RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Microsoft\Office\PowerPoint\Addins\{#PptName}');
    RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Microsoft\Office\Word\Addins\{#WordName}');
    RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Microsoft\Office\PowerPoint\Addins\PowerLaTeX');
    RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Microsoft\Office\Word\Addins\WordLaTeX');
  end;
end;
